<?php require('template/header.phtml') ?>

<div class="jumbotron-fluid">
        <h1 class="display-3">Welcome</h1>
        <p class="lead">This is a forum where you can share you  experiences at live concerts. Discuss events, venues, review past gigs and make new friends.
        To Share posts view images and connect with other fans register here to create an account.</p>
</div>

<?php require('template/footer.phtml') ?>