<?php require('template/header.phtml') ?>
<div class="container" id="postspage">
    <div class="row">

<!--Search for a post-->
        <div class="col-md-6">
            <h1>Posts</h1>
        </div>
        <div class="col-md-8">
            <form action="" class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" name="searchPosts" type="text" placeholder="Search Posts" aria-label="Search">
                <button type="submit" class="btn btn-secondary my-2 my-sm-0" name="SubmitSearchPosts"type="submit">Search</button>
            </form>
        </div>
    </div>

<!--Add a post to the forum-->
    <form action="/addPost.php" method="post">
        <div class="form-group">
            <input class="form-control" type="text" name="subject" placeholder="Subject" required>
            <label for="exampleFormControlTextarea1">Say what you think?</label>
            <textarea class="form-control" name="textArea" id="exampleFormControlTextarea1" rows="3" required></textarea>
            <button type="submit" name="SubmitAddPost" class="btn btn-primary">Add Post</button>
        </div>
    </form>


<!--zView all posts-->
    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
            <?php foreach ($view->postsDataset as $data) : ?>

                <div class="row" id="posts">
                    <div class="col-md-10 mx-auto">
                        <div class="card card-body bg-light mt-5">
                            <h1 class="card-title"><?php echo $data->getPostSubject();?></h1>
                            <!-- Shows images of posts if user logged in otherwise advises user to login to view more details -->
                            <?php if ($_SESSION['email']){
                             echo '<p>Posted by: <?php echo "UserData-" . $data->getUserId();?> <?php echo $data->getPostImage()?></p>';
                            }
                            else{
                                echo '<p>Posted by: Login to view users details';
                            }
                            ?>
                            <p><?php echo $data->getPostText();?></p>
                            <p>Posted on: <?php echo $data->getPostDate();?> </p>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
    </form>
</div>

<?php require('template/footer.phtml') ?>