<?php require('template/header.phtml') ?>
    <div class="container" id="postspage">

<!--        new search bar-->
        <form action="/posts.php" class="" method="post">
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Filter Search</button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#" name="postSearch">Posts</a>
                    <a class="dropdown-item" href="#" name="userSearch">Users</a>
                    <a class="dropdown-item" href="#" name="categorySearch">Categories</a>
                </div>
            </div>
            <input type="text" class="form-control" id="searchPosts" aria-label="Text input with dropdown button" placeholder="Search" onkeyup="showPostSuggestion(this.value)">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" id="submitSearchPosts" type="submit">Search</button>
            </div>
        </div>
            <ul class="list-group" id="textHint"></ul>
        </form>

        <!--Add a post to the forum-->
        <div class="card card-body mt-5 i" id="postCards" style="border-radius: 15px;">
        <?php if ($_SESSION['userID']): ?>
        <form action="/addPost.php" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <input class="form-control" type="text" name="subject" id="postSubjectInput" placeholder="Subject" required>
                <label for="exampleFormControlTextarea1">Say what you think?</label>
                <textarea class="form-control" name="textArea" id="postTextAreaInput" rows="3" required></textarea>
                <button type="submit" name="SubmitAddPost" style="background-color: rgb(220, 143, 52); border: none" class="btn btn-primary" id="submitPostBtn">Post</button>
                <input type="file" name="addImg">
        </form>
    </div>
    </form>
    </div>
<?php else:?>
    <p><a href="/login.php">Login</a> to post content </p>
<?php endif; ?>

    <!--zView all posts-->
    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
        <?php foreach ($view->postsWithUsersDataset as $data) : ?>
            <?php foreach ($view->users->fetchUser($data->getUserId()) as $userData) : ?>
            <div class="row" id="posts">
                <div class="col-md-10 mx-auto">
                    <div class="card card-body mt-5 i" id="postCards" style="border-radius: 15px;">
                        <h2><a href="/userProfile.php?thisUser=<?php echo $userData->getUserID()?>" id="viewPostUserName"> <?php echo '<img src="/media/images/userImages/' . $userData->getProfilePic() . '"class="img-fluid" alt="Responsive image" id="userProfilePicPosts">' . " " . $userData->getUserName(); ?> </a> </h2>
                        <h6><i><?php echo $data->getPostDate() ?></i></h6>
                        <hr>
                        <?php if ($data->getPostImage() != null)
                        echo '<img src="/media/images/postImages/' . $data->getPostImage() . '"class="img-fluid" alt="Responsive image" id="postImage">'; ?>
                        <h1 class="card-title"><a href="" id="viewPostHeading"><?php echo $data->getPostSubject();?></a></h1>
                        <hr>
                        <p><?php echo $data->getPostText()?></p>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
        <?php endforeach; ?>
    </form>
    </div>

    <script src="/js/LiveSearch.js">
    </script>

<?php require('template/footer.phtml') ?>