<?php require('template/header.phtml') ?>

    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card card-body bg-light mt-5">
                <form action="<?php echo $_SERVER['PHP_SELF']; ?>" name="register" method="post">
                    <h1 class="h3 mb-3 font-weight-normal">Register</h1>
                    <p>Please fill out the details below to register for an account.</p>
                    <div class="form-group">
                        <label for="firstName">First Name:</label>
                        <input type="text" id="inputName" class="form-control" <?php echo (!empty($error['firstNameError'])) ? 'is-invalid' : ''; ?>
                               name="firstName" placeholder="Enter First Name" required autofocus>
                        <span class="invalid-feedback"><?php echo $error['firstNameError']; ?></span>
                    </div>
                    <div class="form-group">
                        <label for="firstName">Surname:</label>
                        <input type="text" id="inputSurname" class="form-control" <?php echo (!empty($error['firstNameError'])) ? 'is-invalid' : ''; ?> name="lastName" placeholder="Enter Last Name" required>
                    </div>
                    <div class="form-group">
                        <label for="firstName">Email:</label>
                        <input type="email" id="inputEmail" class="form-control" <?php echo (!empty($error['firstNameError'])) ? 'is-invalid' : ''; ?>name="email" placeholder="Enter Email" required>
                    </div>
                    <div class="form-group">
                        <label for="firstName">Confirm Email:</label>
                        <input type="email" id="confirmEmail" class="form-control" <?php echo (!empty($error['firstNameError'])) ? 'is-invalid' : ''; ?> name="confirmEmail" placeholder="Confirm Email" required>
                    </div>
                    <div class="form-group">
                        <label for="firstName">Password:</label>
                        <input type="password" id="inputPassword" class="form-control" <?php echo (!empty($error['firstNameError'])) ? 'is-invalid' : ''; ?> name="password" placeholder="Enter Password" required>
                    </div>
                    <div class="form-group">
                        <label for="firstName">Confirm Password:</label>
                        <input type="password" id="confirmPassword" class="form-control" name="confirmPassword" placeholder="Confirm Password" required>
                    </div>

                    <div class="row">
                        <div class="col">
                            <input type="submit" name="registerSubmit" value="Register" class="btn btn-success btn-block">
                        </div>
                        <div class="col">
                            <a href="/login.php" class="btn btn-light btn-block">Log in</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

<?php require('template/footer.phtml') ?>