<?php require('template/header.phtml') ?>

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    <?php foreach ($view->postsWithUsersDataset as $data) : ?>
        <?php foreach ($view->users->fetchUser($data->getUserId()) as $userData) : ?>
            <div class="row" id="posts">
                <div class="col-md-10 mx-auto">
                    <div class="card card-body mt-5 i" id="postCards" style="border-radius: 15px;">
                        <h2><a href="/userProfile.php?thisUser=<?php echo $userData->getUserID()?>" id="viewPostUserName"> <?php echo '<img src="/media/images/userImages/' . $userData->getProfilePic() . '"class="img-fluid" alt="Responsive image" id="userProfilePicPosts">' . " " . $userData->getUserName(); ?> </a> </h2>
                        <h6><i><?php echo $data->getPostDate() ?></i></h6>
                        <hr>
                        <?php if ($data->getPostImage() != null)
                            echo '<img src="/media/images/postImages/' . $data->getPostImage() . '"class="img-fluid" alt="Responsive image" id="postImage">'; ?>
                        <h1 class="card-title"><a href="" id="viewPostHeading"><?php echo $data->getPostSubject();?></a></h1>
                        <hr>
                        <p><?php echo $data->getPostText()?></p>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    <?php endforeach; ?>
</form>

<?php require('template/footer.phtml') ?>
