<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap-css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap grid -->
    <link href="/css/bootstrap-css/bootstrap-grid.css" rel="stylesheet">
    <!-- Bootstrap reboot -->
    <link href="/css/bootstrap-css/bootstrap-reboot.css" rel="stylesheet">
    <!-- My Stylesheet -->
    <link href="/css/my-stylesheet.css" rel="stylesheet">

    <title>Server-Side Programming - <?php echo $view->pageTitle; ?></title>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <div class="container">
    <a class="navbar-brand" href="#">Live Music Forum</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/index.php">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/about.php">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/posts.php">Posts</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <?php
            if ($_SESSION['email']){
                echo '<li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">' . $_SESSION['name'] . '</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
                <a class="dropdown-item" href="/profile.php">Profile</a>
                <a class="dropdown-item" href="#">Account Settings</a>
                <a class="dropdown-item" href="/logout.php">Log out</a>
            </div>
            </li>';
            }
            else{
                echo '<li class="nav-item">
                <a class="nav-link" href="/register.php">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/login.php">Login</a>
            </li>';
            }
            ?>
        </ul>
    </div>
    </div>
</nav>

<main>
<div class="container">

